from enum import Enum
from pydantic import BaseModel, Field
class MacroRegime(str, Enum):
    BULLISH_TREND = "BULLISH_TREND"
    BEARISH_PULLBACK = "BEARISH_PULLBACK"
    RANGE_BOUND = "RANGE_BOUND"
class MicroSignal(str, Enum):
    BULLISH_REVERSAL_CONFIRMED = "BULLISH_REVERSAL_CONFIRMED"
    BULLISH_CONTINUATION = "BULLISH_CONTINUATION"
    BEARISH_REVERSAL_CONFIRMED = "BEARISH_REVERSAL_CONFIRMED"
    SHORT_CONTINUATION = "SHORT_CONTINUATION"
